// frontend/src/pages/ExplorePage.jsx
import React, { useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import Layout from '../components/Layout';

function HorizontalScroller({ children, style }) {
  const sliderRef = useRef(null);
  let isDown = false;
  let startX;
  let scrollLeft;

  const handleMouseDown = (e) => {
    isDown = true;
    if (sliderRef.current) {
      sliderRef.current.style.cursor = 'grabbing';
      startX = e.pageX - sliderRef.current.offsetLeft;
      scrollLeft = sliderRef.current.scrollLeft;
    }
  };

  const handleMouseLeave = () => {
    isDown = false;
    if (sliderRef.current) sliderRef.current.style.cursor = 'grab';
  };

  const handleMouseUp = () => {
    isDown = false;
    if (sliderRef.current) sliderRef.current.style.cursor = 'grab';
  };

  const handleMouseMove = (e) => {
    if (!isDown || !sliderRef.current) return;
    e.preventDefault();
    const x = e.pageX - sliderRef.current.offsetLeft;
    const walk = (x - startX) * 1;
    sliderRef.current.scrollLeft = scrollLeft - walk;
  };

  const handleWheel = (e) => {
    if (sliderRef.current) {
      sliderRef.current.scrollLeft += e.deltaY;
    }
  };

  return (
    <div 
      className="horizontal-scroller" 
      ref={sliderRef}
      onMouseDown={handleMouseDown}
      onMouseLeave={handleMouseLeave}
      onMouseUp={handleMouseUp}
      onMouseMove={handleMouseMove}
      onWheel={handleWheel}
      style={style}
    >
      {children}
    </div>
  );
}

function ExplorePage() {
  const navigate = useNavigate();
  const rows = Array.from({ length: 3 });
  const cardsPerRow = Array.from({ length: 20 });

  return (
    <Layout sidebarType="explore" showFab={false}>
      {rows.map((_, rowIndex) => (
        <HorizontalScroller key={rowIndex} style={{ marginTop: rowIndex === 0 ? '0' : '20px' }}>
          {cardsPerRow.map((_, cardIndex) => (
            <div key={cardIndex} className="explore-card">
              <div className="explore-header">
                <div className="explore-avatar" onClick={() => navigate('/personal')}></div>
                <div className="explore-title-area">
                  <div className="explore-title">社群名稱</div>
                  <div className="explore-tags">#社群標籤 </div>
                </div>
              </div>
              <div className="explore-details">
                <div className="explore-desc">社群簡介</div>
                <div className="explore-members">
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                    <circle cx="9" cy="7" r="4"></circle>
                    <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                    <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                  </svg>
                  <span>555名成員</span>
                </div>
                <button className="post-action-btn-large" onClick={() => navigate('/social')}>探索</button>
              </div>
            </div>
          ))}
        </HorizontalScroller>
      ))}
    </Layout>
  );
}

export default ExplorePage;

// src/views/ExplorePage.vue
<script setup>
import { onBeforeUnmount, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import AppNavbar from '../components/AppNavbar.vue'
import { usePageCss } from '../composables/usePageCss'

usePageCss('explore_page.css', { materialIcons: true })

const router = useRouter()
const cleanupHandlers = []

onMounted(() => {
  document.querySelectorAll('.horizontal-scroller').forEach((slider) => {
    let isDown = false
    let startX = 0
    let scrollLeft = 0

    const onMouseDown = (event) => {
      isDown = true
      slider.style.cursor = 'grabbing'
      startX = event.pageX - slider.offsetLeft
      scrollLeft = slider.scrollLeft
      event.preventDefault()
    }

    const onMouseUp = () => {
      if (isDown) {
        isDown = false
        slider.style.cursor = 'grab'
      }
    }

    const onMouseMove = (event) => {
      if (!isDown) return
      event.preventDefault()
      const x = event.pageX - slider.offsetLeft
      slider.scrollLeft = scrollLeft - (x - startX)
    }

    const onWheel = (event) => {
      event.preventDefault()
      slider.scrollLeft += event.deltaY
    }

    slider.addEventListener('mousedown', onMouseDown)
    window.addEventListener('mouseup', onMouseUp)
    window.addEventListener('mousemove', onMouseMove)
    slider.addEventListener('wheel', onWheel, { passive: false })

    cleanupHandlers.push(() => {
      slider.removeEventListener('mousedown', onMouseDown)
      window.removeEventListener('mouseup', onMouseUp)
      window.removeEventListener('mousemove', onMouseMove)
      slider.removeEventListener('wheel', onWheel)
    })
  })
})

onBeforeUnmount(() => {
  cleanupHandlers.splice(0).forEach((cleanup) => cleanup())
})
</script>

<template>
  <div class="app-container">
    <AppNavbar />
    <div class="main-layout">
      <div class="sidebar">
        <div class="sidebar-search">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#7A7A7A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-right: 10px;"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>
          <input type="text" class="sidebar-search-input" placeholder="">
        </div>
        <div class="grid-icons">
          <div v-for="item in 20" :key="item" class="grid-item">
            <div class="grid-icon-circle"></div>
            <div style="font-size: 14px; color: #333; margin-top: 5px;">分類</div>
          </div>
        </div>
      </div>

      <div class="feed-content">
        <div v-for="row in 3" :key="row" class="horizontal-scroller" :style="{ marginTop: row === 1 ? '0' : '20px' }">
          <div v-for="card in 20" :key="card" class="explore-card">
            <div class="explore-header">
              <div class="explore-avatar" @click="router.push('/personal')"></div>
              <div class="explore-title-area">
                <div class="explore-title">主題社群</div>
                <div class="explore-tags">#興趣標籤</div>
              </div>
            </div>
            <div class="explore-details">
              <div class="explore-desc">社群簡介</div>
              <div class="explore-members">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                <span>555 人</span>
              </div>
              <button class="post-action-btn-large" @click="router.push('/social')">進入</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
